dist: trusty
language: node_js
node_js:
  - "8"
cache: yarn
after_success:
  - yarn build
  - cp deployment-package.json build/package.json
  - cd build && npx now-cd --team=auth0-design
notifications:
  email: false
branches:
  only:
    - master
